[launcher]
author=JFrog
description=JFrog Security Analytics for Splunk - Provides dashboards, searches, and analytics for JFrog Artifactory and Xray security events.
version=1.0.0

[package]
id=jfrog_security_analytics_for_splunk

[ui]
is_visible=1
label=JFrog Security Analytics

[triggers]
reload.transforms = simple
reload.props = simple
reload.lookups = simple
