# Event types for JFrog Security Analytics for Splunk

[jfrog_xray_critical_violation]
search = sourcetype="jfrog:xray:violations" severity="Critical"
tags = jfrog xray violation critical security

[jfrog_xray_high_violation]
search = sourcetype="jfrog:xray:violations" severity="High"
tags = jfrog xray violation high security

[jfrog_xray_license_violation]
search = sourcetype="jfrog:xray:violations" violation_type="License Violated"
tags = jfrog xray violation license

[jfrog_artifactory_denied_access]
search = sourcetype="jfrog:artifactory:access" action_response="DENIED"
tags = jfrog artifactory access denied

[jfrog_artifactory_deploy]
search = sourcetype="jfrog:artifactory:request" request_content_length>0 request_method="PUT"
tags = jfrog artifactory deploy upload
