# Macros configuration for JFrog Security Analytics for Splunk

[jfrog_xray_violations_index]
definition = index=jfrog sourcetype="jfrog:xray:violations"
iseval = 0

[jfrog_xray_siem_index]
definition = index=jfrog sourcetype="jfrog:xray:siem"
iseval = 0

[jfrog_artifactory_access_index]
definition = index=jfrog sourcetype="jfrog:artifactory:access"
iseval = 0

[jfrog_artifactory_request_index]
definition = index=jfrog sourcetype="jfrog:artifactory:request"
iseval = 0

[jfrog_artifactory_traffic_index]
definition = index=jfrog sourcetype="jfrog:artifactory:traffic"
iseval = 0

[jfrog_all_index]
definition = index=jfrog sourcetype="jfrog:*"
iseval = 0

[jfrog_high_severity]
definition = (severity="High" OR severity="Critical")
iseval = 0

[jfrog_critical_severity]
definition = severity="Critical"
iseval = 0
