# Tags configuration for JFrog Security Analytics for Splunk

[eventtype=jfrog_xray_critical_violation]
jfrog = enabled
xray = enabled
violation = enabled
critical = enabled
security = enabled

[eventtype=jfrog_xray_high_violation]
jfrog = enabled
xray = enabled
violation = enabled
high = enabled
security = enabled

[eventtype=jfrog_xray_license_violation]
jfrog = enabled
xray = enabled
violation = enabled
license = enabled

[eventtype=jfrog_artifactory_denied_access]
jfrog = enabled
artifactory = enabled
access = enabled
denied = enabled

[eventtype=jfrog_artifactory_deploy]
jfrog = enabled
artifactory = enabled
deploy = enabled
